"""create_money_harmony_schema

Revision ID: 091abbeecadc
Revises: 
Create Date: 2026-09-28 16:13:03.654765
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '091abbeecadc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mh_users',
    sa.Column('display_name', sa.String(length=120), server_default='', nullable=False),
    sa.Column('email', sa.String(length=320), server_default='', nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('language', sa.String(length=5), server_default='en', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("email = lower(trim(email)) AND position('@' in email) > 1", name=op.f('ck_mh_users_normalized_email')),
    sa.CheckConstraint("language IN ('ar', 'en')", name=op.f('ck_mh_users_language')),
    sa.CheckConstraint("password_hash LIKE '$argon2id$%%' OR password_hash LIKE '$2b$%%'", name=op.f('ck_mh_users_password_hash_format')),
    sa.CheckConstraint("status IN ('active', 'disabled', 'deleted')", name=op.f('ck_mh_users_status')),
    sa.CheckConstraint('length(trim(display_name)) > 0', name=op.f('ck_mh_users_name_required')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_users')),
    sa.UniqueConstraint('email')
    )
    op.create_table('mh_households',
    sa.Column('name', sa.String(length=120), server_default='', nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='SAR', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_mh_households_currency_code')),
    sa.CheckConstraint("status IN ('active', 'archived')", name=op.f('ck_mh_households_status')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_mh_households_name_required')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['mh_users.id'], name=op.f('fk_mh_households_owner_user_id_mh_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_households'))
    )
    op.create_index(op.f('ix_mh_households_owner_user_id'), 'mh_households', ['owner_user_id'], unique=False)
    op.create_table('mh_notification_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), server_default='system', nullable=False),
    sa.Column('channel', sa.String(length=10), server_default='in_app', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('in_app', 'email', 'push')", name=op.f('ck_mh_notification_preferences_channel')),
    sa.CheckConstraint("kind IN ('partner_invitation', 'invitation_accepted', 'partner_transaction', 'budget_warning', 'budget_exceeded', 'monthly_summary', 'reminder', 'system')", name=op.f('ck_mh_notification_preferences_kind')),
    sa.ForeignKeyConstraint(['user_id'], ['mh_users.id'], name=op.f('fk_mh_notification_preferences_user_id_mh_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_notification_preferences')),
    sa.UniqueConstraint('user_id', 'kind', 'channel', name='uq_mh_preference_user_kind_channel')
    )
    op.create_table('mh_user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_token_hash', sa.String(length=64), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("access_token_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_mh_user_sessions_access_digest')),
    sa.CheckConstraint("refresh_token_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_mh_user_sessions_refresh_digest')),
    sa.CheckConstraint('access_expires_at > created_at AND refresh_expires_at >= access_expires_at', name=op.f('ck_mh_user_sessions_expiry')),
    sa.CheckConstraint('access_token_hash <> refresh_token_hash', name=op.f('ck_mh_user_sessions_distinct_tokens')),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= created_at', name=op.f('ck_mh_user_sessions_revocation_time')),
    sa.ForeignKeyConstraint(['user_id'], ['mh_users.id'], name=op.f('fk_mh_user_sessions_user_id_mh_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_user_sessions')),
    sa.UniqueConstraint('access_token_hash'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('ix_mh_sessions_expiry', 'mh_user_sessions', ['refresh_expires_at'], unique=False)
    op.create_index('ix_mh_sessions_user_revoked', 'mh_user_sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_table('mh_categories',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('kind', sa.String(length=10), server_default='expense', nullable=False),
    sa.Column('icon', sa.String(length=64), server_default='tag', nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('income', 'expense')", name=op.f('ck_mh_categories_kind')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_mh_categories_name_required')),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_categories_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_categories')),
    sa.UniqueConstraint('household_id', 'id', 'kind', name='uq_mh_category_tenant_kind')
    )
    op.create_index('ix_mh_category_household_archived', 'mh_categories', ['household_id', 'is_archived'], unique=False)
    op.create_index('uq_mh_category_name', 'mh_categories', ['household_id', 'kind', sa.literal_column('lower(trim(name))')], unique=True)
    op.create_table('mh_household_memberships',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), server_default='partner', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'active' AND ended_at IS NULL) OR (status <> 'active' AND ended_at IS NOT NULL)", name=op.f('ck_mh_household_memberships_ended_status')),
    sa.CheckConstraint("role <> 'owner' OR status = 'active'", name=op.f('ck_mh_household_memberships_active_owner')),
    sa.CheckConstraint("role IN ('owner', 'partner')", name=op.f('ck_mh_household_memberships_role')),
    sa.CheckConstraint("status IN ('active', 'left', 'removed')", name=op.f('ck_mh_household_memberships_status')),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_household_memberships_household_id_mh_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['mh_users.id'], name=op.f('fk_mh_household_memberships_user_id_mh_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_household_memberships')),
    sa.UniqueConstraint('household_id', 'user_id', 'role', name='uq_mh_membership_owner_target'),
    sa.UniqueConstraint('household_id', 'user_id', name='uq_mh_membership_household_user')
    )
    op.create_index('ix_mh_membership_user_status', 'mh_household_memberships', ['user_id', 'status'], unique=False)
    op.create_index('uq_mh_membership_single_owner', 'mh_household_memberships', ['household_id'], unique=True, postgresql_where=sa.text("role = 'owner'"))
    op.create_table('mh_financial_accounts',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), server_default='', nullable=False),
    sa.Column('account_type', sa.String(length=20), server_default='cash', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='SAR', nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=19, scale=4), server_default='0', nullable=False),
    sa.Column('opening_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_type IN ('cash', 'bank', 'credit_card', 'savings', 'other')", name=op.f('ck_mh_financial_accounts_type')),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_mh_financial_accounts_currency_code')),
    sa.CheckConstraint("opening_balance <> 'NaN'::numeric", name=op.f('ck_mh_financial_accounts_finite_balance')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_mh_financial_accounts_name_required')),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_financial_accounts_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_financial_accounts_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_financial_accounts')),
    sa.UniqueConstraint('household_id', 'id', name='uq_mh_account_tenant_id')
    )
    op.create_index('ix_mh_accounts_household_archived', 'mh_financial_accounts', ['household_id', 'is_archived'], unique=False)
    op.create_table('mh_monthly_category_budgets',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('category_kind', sa.String(length=10), server_default='expense', nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), server_default=sa.text('EXTRACT(YEAR FROM CURRENT_DATE)::integer'), nullable=False),
    sa.Column('month', sa.Integer(), server_default=sa.text('EXTRACT(MONTH FROM CURRENT_DATE)::integer'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), server_default='0', nullable=False),
    sa.Column('alert_threshold_percent', sa.Integer(), server_default='80', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("amount >= 0 AND amount <> 'NaN'::numeric", name=op.f('ck_mh_monthly_category_budgets_nonnegative_amount')),
    sa.CheckConstraint("category_kind = 'expense'", name=op.f('ck_mh_monthly_category_budgets_expense_only')),
    sa.CheckConstraint('alert_threshold_percent BETWEEN 1 AND 100', name=op.f('ck_mh_monthly_category_budgets_threshold')),
    sa.CheckConstraint('month BETWEEN 1 AND 12 AND year BETWEEN 1900 AND 9999', name=op.f('ck_mh_monthly_category_budgets_period')),
    sa.ForeignKeyConstraint(['household_id', 'category_id', 'category_kind'], ['mh_categories.household_id', 'mh_categories.id', 'mh_categories.kind'], name=op.f('fk_mh_monthly_category_budgets_household_id_mh_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_monthly_category_budgets_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_monthly_category_budgets_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_monthly_category_budgets')),
    sa.UniqueConstraint('household_id', 'category_id', 'year', 'month', name='uq_mh_budget_category_month'),
    sa.UniqueConstraint('household_id', 'id', name='uq_mh_budget_tenant_id')
    )
    op.create_index('ix_mh_budgets_creator', 'mh_monthly_category_budgets', ['household_id', 'created_by_user_id'], unique=False)
    op.create_index('ix_mh_budgets_tenant_period', 'mh_monthly_category_budgets', ['household_id', 'year', 'month'], unique=False)
    op.create_table('mh_partner_invitations',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('accepted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=320), server_default='', nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP + INTERVAL '7 days'"), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'accepted' AND accepted_by_user_id IS NOT NULL AND resolved_at < expires_at) OR (status <> 'accepted' AND accepted_by_user_id IS NULL)", name=op.f('ck_mh_partner_invitations_acceptance')),
    sa.CheckConstraint("(status = 'pending' AND resolved_at IS NULL) OR (status <> 'pending' AND resolved_at IS NOT NULL)", name=op.f('ck_mh_partner_invitations_resolution')),
    sa.CheckConstraint("email = lower(trim(email)) AND position('@' in email) > 1", name=op.f('ck_mh_partner_invitations_normalized_email')),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'declined', 'expired', 'revoked')", name=op.f('ck_mh_partner_invitations_status')),
    sa.CheckConstraint("token_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_mh_partner_invitations_token_digest')),
    sa.CheckConstraint('accepted_by_user_id IS NULL OR accepted_by_user_id <> invited_by_user_id', name=op.f('ck_mh_partner_invitations_not_self')),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_mh_partner_invitations_expiry')),
    sa.ForeignKeyConstraint(['household_id', 'accepted_by_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name='fk_mh_invitation_acceptor_membership', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'invited_by_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name='fk_mh_invitation_inviter_membership', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_partner_invitations_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_partner_invitations')),
    sa.UniqueConstraint('household_id', 'id', name='uq_mh_invitation_tenant_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_mh_invitation_email_status', 'mh_partner_invitations', ['email', 'status'], unique=False)
    op.create_index('ix_mh_invitation_expiry', 'mh_partner_invitations', ['status', 'expires_at'], unique=False)
    op.create_index('uq_mh_invitation_pending', 'mh_partner_invitations', ['household_id', 'email'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('mh_transactions',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=10), server_default='expense', nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), server_default='0', nullable=False),
    sa.Column('transaction_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("amount > 0 AND amount <> 'NaN'::numeric", name=op.f('ck_mh_transactions_positive_amount')),
    sa.CheckConstraint("kind IN ('income', 'expense')", name=op.f('ck_mh_transactions_kind')),
    sa.ForeignKeyConstraint(['household_id', 'account_id'], ['mh_financial_accounts.household_id', 'mh_financial_accounts.id'], name=op.f('fk_mh_transactions_household_id_mh_financial_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'category_id', 'kind'], ['mh_categories.household_id', 'mh_categories.id', 'mh_categories.kind'], name=op.f('fk_mh_transactions_household_id_mh_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_transactions_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_transactions_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_transactions')),
    sa.UniqueConstraint('household_id', 'id', name='uq_mh_transaction_tenant_id')
    )
    op.create_index('ix_mh_transactions_account_date', 'mh_transactions', ['household_id', 'account_id', 'transaction_date'], unique=False)
    op.create_index('ix_mh_transactions_category_date', 'mh_transactions', ['household_id', 'category_id', 'kind', 'transaction_date'], unique=False)
    op.create_index('ix_mh_transactions_creator', 'mh_transactions', ['household_id', 'created_by_user_id'], unique=False)
    op.create_index('ix_mh_transactions_tenant_date', 'mh_transactions', ['household_id', 'transaction_date', 'id'], unique=False)
    op.create_table('mh_notifications',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('member_user_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('budget_id', sa.Uuid(), nullable=True),
    sa.Column('invitation_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=32), server_default='system', nullable=False),
    sa.Column('channel', sa.String(length=10), server_default='in_app', nullable=False),
    sa.Column('title', sa.String(length=200), server_default='', nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('delivery_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'partner_invitation' AND invitation_id IS NOT NULL AND transaction_id IS NULL AND budget_id IS NULL) OR (kind <> 'partner_invitation' AND member_user_id IS NOT NULL)", name=op.f('ck_mh_notifications_recipient_scope')),
    sa.CheckConstraint("channel IN ('in_app', 'email', 'push')", name=op.f('ck_mh_notifications_channel')),
    sa.CheckConstraint("delivery_status IN ('pending', 'sent', 'failed', 'suppressed')", name=op.f('ck_mh_notifications_delivery_status')),
    sa.CheckConstraint("kind IN ('partner_invitation', 'invitation_accepted', 'partner_transaction', 'budget_warning', 'budget_exceeded', 'monthly_summary', 'reminder', 'system')", name=op.f('ck_mh_notifications_kind')),
    sa.CheckConstraint('length(trim(title)) > 0', name=op.f('ck_mh_notifications_title_required')),
    sa.CheckConstraint('member_user_id IS NULL OR member_user_id = recipient_user_id', name=op.f('ck_mh_notifications_recipient_member')),
    sa.CheckConstraint('read_at IS NULL OR read_at >= created_at', name=op.f('ck_mh_notifications_read_time')),
    sa.ForeignKeyConstraint(['household_id', 'budget_id'], ['mh_monthly_category_budgets.household_id', 'mh_monthly_category_budgets.id'], name=op.f('fk_mh_notifications_household_id_mh_monthly_category_budgets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'invitation_id'], ['mh_partner_invitations.household_id', 'mh_partner_invitations.id'], name=op.f('fk_mh_notifications_household_id_mh_partner_invitations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'member_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_notifications_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'transaction_id'], ['mh_transactions.household_id', 'mh_transactions.id'], name=op.f('fk_mh_notifications_household_id_mh_transactions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_notifications_household_id_mh_households'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['mh_users.id'], name=op.f('fk_mh_notifications_recipient_user_id_mh_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_notifications'))
    )
    op.create_index('ix_mh_notification_delivery', 'mh_notifications', ['delivery_status', 'scheduled_at'], unique=False)
    op.create_index('ix_mh_notification_inbox', 'mh_notifications', ['recipient_user_id', 'household_id', 'read_at', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mh_notification_inbox', table_name='mh_notifications')
    op.drop_index('ix_mh_notification_delivery', table_name='mh_notifications')
    op.drop_table('mh_notifications')
    op.drop_index('ix_mh_transactions_tenant_date', table_name='mh_transactions')
    op.drop_index('ix_mh_transactions_creator', table_name='mh_transactions')
    op.drop_index('ix_mh_transactions_category_date', table_name='mh_transactions')
    op.drop_index('ix_mh_transactions_account_date', table_name='mh_transactions')
    op.drop_table('mh_transactions')
    op.drop_index('uq_mh_invitation_pending', table_name='mh_partner_invitations', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_mh_invitation_expiry', table_name='mh_partner_invitations')
    op.drop_index('ix_mh_invitation_email_status', table_name='mh_partner_invitations')
    op.drop_table('mh_partner_invitations')
    op.drop_index('ix_mh_budgets_tenant_period', table_name='mh_monthly_category_budgets')
    op.drop_index('ix_mh_budgets_creator', table_name='mh_monthly_category_budgets')
    op.drop_table('mh_monthly_category_budgets')
    op.drop_index('ix_mh_accounts_household_archived', table_name='mh_financial_accounts')
    op.drop_table('mh_financial_accounts')
    op.drop_index('uq_mh_membership_single_owner', table_name='mh_household_memberships', postgresql_where=sa.text("role = 'owner'"))
    op.drop_index('ix_mh_membership_user_status', table_name='mh_household_memberships')
    op.drop_table('mh_household_memberships')
    op.drop_index('uq_mh_category_name', table_name='mh_categories')
    op.drop_index('ix_mh_category_household_archived', table_name='mh_categories')
    op.drop_table('mh_categories')
    op.drop_index('ix_mh_sessions_user_revoked', table_name='mh_user_sessions')
    op.drop_index('ix_mh_sessions_expiry', table_name='mh_user_sessions')
    op.drop_table('mh_user_sessions')
    op.drop_table('mh_notification_preferences')
    op.drop_index(op.f('ix_mh_households_owner_user_id'), table_name='mh_households')
    op.drop_table('mh_households')
    op.drop_table('mh_users')
    # ### end Alembic commands ###
