"""add_tenant_scoped_transaction_receipts

Revision ID: 442f008114e7
Revises: fbb2c9cb70ba
Create Date: 2026-10-02 12:18:16.834579
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '442f008114e7'
down_revision: Union[str, Sequence[str], None] = 'fbb2c9cb70ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mh_transaction_receipts',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mime_type IN ('image/png', 'image/jpeg', 'application/pdf', 'image/webp')", name=op.f('ck_mh_transaction_receipts_allowed_mime_type')),
    sa.CheckConstraint('length(trim(filename)) > 0', name=op.f('ck_mh_transaction_receipts_filename_required')),
    sa.CheckConstraint('octet_length(content) = size_bytes', name=op.f('ck_mh_transaction_receipts_content_size_matches')),
    sa.CheckConstraint('size_bytes BETWEEN 1 AND 5242880', name=op.f('ck_mh_transaction_receipts_size_bytes_range')),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_transaction_receipts_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'transaction_id'], ['mh_transactions.household_id', 'mh_transactions.id'], name=op.f('fk_mh_transaction_receipts_household_id_mh_transactions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_transaction_receipts_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_transaction_receipts')),
    sa.UniqueConstraint('household_id', 'transaction_id', name='uq_mh_receipt_transaction')
    )
    op.create_index('ix_mh_transaction_receipts_household_created', 'mh_transaction_receipts', ['household_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mh_transaction_receipts_household_created', table_name='mh_transaction_receipts')
    op.drop_table('mh_transaction_receipts')
    # ### end Alembic commands ###
