"""add_debts_installments_payments

Revision ID: 5bbbdcd262ed
Revises: c7c95525da13
Create Date: 2026-09-30 09:02:07.690685
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5bbbdcd262ed'
down_revision: Union[str, Sequence[str], None] = 'c7c95525da13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mh_debts',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('counterparty', sa.String(length=120), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('principal', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('first_due_date', sa.Date(), nullable=False),
    sa.Column('installment_count', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('payable', 'receivable')", name=op.f('ck_mh_debts_direction')),
    sa.CheckConstraint("principal > 0 AND principal < 1000000000000000 AND principal <> 'NaN'::numeric", name=op.f('ck_mh_debts_positive_finite_principal')),
    sa.CheckConstraint('installment_count BETWEEN 1 AND 120', name=op.f('ck_mh_debts_installment_count')),
    sa.CheckConstraint('length(trim(counterparty)) > 0', name=op.f('ck_mh_debts_counterparty_required')),
    sa.CheckConstraint('length(trim(title)) > 0', name=op.f('ck_mh_debts_title_required')),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_debts_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_debts_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_debts')),
    sa.UniqueConstraint('household_id', 'id', name='uq_mh_debt_tenant_id')
    )
    op.create_index('ix_mh_debts_household_archived', 'mh_debts', ['household_id', 'is_archived'], unique=False)
    op.create_table('mh_debt_installments',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('debt_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("amount > 0 AND amount < 'Infinity'::numeric AND amount <> 'NaN'::numeric", name=op.f('ck_mh_debt_installments_positive_finite_amount')),
    sa.CheckConstraint('sequence_no > 0', name=op.f('ck_mh_debt_installments_positive_sequence')),
    sa.ForeignKeyConstraint(['household_id', 'debt_id'], ['mh_debts.household_id', 'mh_debts.id'], name=op.f('fk_mh_debt_installments_household_id_mh_debts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_debt_installments_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_debt_installments')),
    sa.UniqueConstraint('household_id', 'debt_id', 'sequence_no', name='uq_mh_debt_installment_sequence')
    )
    op.create_index('ix_mh_debt_installments_household_due', 'mh_debt_installments', ['household_id', 'due_date'], unique=False)
    op.create_table('mh_debt_payments',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('debt_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("amount > 0 AND amount < 'Infinity'::numeric AND amount <> 'NaN'::numeric", name=op.f('ck_mh_debt_payments_positive_finite_amount')),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_debt_payments_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'debt_id'], ['mh_debts.household_id', 'mh_debts.id'], name=op.f('fk_mh_debt_payments_household_id_mh_debts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_debt_payments_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_debt_payments'))
    )
    op.create_index('ix_mh_debt_payments_household_debt_paid', 'mh_debt_payments', ['household_id', 'debt_id', 'paid_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mh_debt_payments_household_debt_paid', table_name='mh_debt_payments')
    op.drop_table('mh_debt_payments')
    op.drop_index('ix_mh_debt_installments_household_due', table_name='mh_debt_installments')
    op.drop_table('mh_debt_installments')
    op.drop_index('ix_mh_debts_household_archived', table_name='mh_debts')
    op.drop_table('mh_debts')
    # ### end Alembic commands ###
