"""add_household_planning_and_settlement_models

Revision ID: 82a72bdd71cb
Revises: bc746110ce85
Create Date: 2026-10-08 03:36:52.381001
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '82a72bdd71cb'
down_revision: Union[str, Sequence[str], None] = 'bc746110ce85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mh_safe_balance_settings',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('payday_day', sa.Integer(), nullable=False),
    sa.Column('monthly_essentials', sa.Numeric(precision=19, scale=4), server_default='0', nullable=False),
    sa.Column('additional_due_allocation', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("additional_due_allocation IS NULL OR (additional_due_allocation >= 0 AND additional_due_allocation < 'Infinity'::numeric AND additional_due_allocation <> 'NaN'::numeric)", name=op.f('ck_mh_safe_balance_settings_nonnegative_finite_allocation')),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_mh_safe_balance_settings_currency_code')),
    sa.CheckConstraint("monthly_essentials >= 0 AND monthly_essentials < 'Infinity'::numeric AND monthly_essentials <> 'NaN'::numeric", name=op.f('ck_mh_safe_balance_settings_nonnegative_finite_essentials')),
    sa.CheckConstraint('payday_day BETWEEN 1 AND 31', name=op.f('ck_mh_safe_balance_settings_payday_day_range')),
    sa.ForeignKeyConstraint(['household_id', 'user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_safe_balance_settings_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_safe_balance_settings_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_safe_balance_settings')),
    sa.UniqueConstraint('household_id', 'user_id', 'currency', name='uq_mh_safe_balance_person_currency')
    )
    op.create_index('ix_mh_safe_balance_settings_user', 'mh_safe_balance_settings', ['user_id', 'household_id'], unique=False)
    op.create_table('mh_household_tasks',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('assignee_user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('details', sa.Text(), server_default='', nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='pending', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_mh_household_tasks_currency_code')),
    sa.CheckConstraint("status IN ('pending', 'complete')", name=op.f('ck_mh_household_tasks_status')),
    sa.CheckConstraint('length(trim(title)) > 0', name=op.f('ck_mh_household_tasks_title_required')),
    sa.ForeignKeyConstraint(['household_id', 'account_id'], ['mh_financial_accounts.household_id', 'mh_financial_accounts.id'], name=op.f('fk_mh_household_tasks_household_id_mh_financial_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'assignee_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name='fk_mh_tasks_assignee_membership', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name='fk_mh_tasks_creator_membership', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_household_tasks_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_household_tasks')),
    sa.UniqueConstraint('household_id', 'id', name='uq_mh_task_tenant_id')
    )
    op.create_index('ix_mh_tasks_tenant_account', 'mh_household_tasks', ['household_id', 'account_id'], unique=False)
    op.create_index('ix_mh_tasks_tenant_assignee', 'mh_household_tasks', ['household_id', 'assignee_user_id'], unique=False)
    op.create_index('ix_mh_tasks_tenant_creator', 'mh_household_tasks', ['household_id', 'created_by_user_id'], unique=False)
    op.create_index('ix_mh_tasks_tenant_status_due', 'mh_household_tasks', ['household_id', 'status', 'due_date'], unique=False)
    op.create_table('mh_bill_split_rules',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('bill_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('mode', sa.String(length=10), server_default='equal', nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_mh_bill_split_rules_currency_code')),
    sa.CheckConstraint("mode IN ('equal', 'income')", name=op.f('ck_mh_bill_split_rules_mode')),
    sa.ForeignKeyConstraint(['household_id', 'bill_id'], ['mh_bills.household_id', 'mh_bills.id'], name=op.f('fk_mh_bill_split_rules_household_id_mh_bills'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_bill_split_rules_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_bill_split_rules_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_bill_split_rules')),
    sa.UniqueConstraint('household_id', 'bill_id', name='uq_mh_bill_split_rule_bill'),
    sa.UniqueConstraint('household_id', 'id', name='uq_mh_bill_split_rule_tenant_id')
    )
    op.create_index('ix_mh_bill_split_rules_creator', 'mh_bill_split_rules', ['household_id', 'created_by_user_id'], unique=False)
    op.create_index('ix_mh_bill_split_rules_currency', 'mh_bill_split_rules', ['household_id', 'currency'], unique=False)
    op.create_table('mh_bill_split_shares',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('member_user_id', sa.Uuid(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('declared_income', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('share_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("declared_income IS NULL OR (declared_income >= 0 AND declared_income < 'Infinity'::numeric AND declared_income <> 'NaN'::numeric)", name=op.f('ck_mh_bill_split_shares_nonnegative_finite_income')),
    sa.CheckConstraint("percentage BETWEEN 0 AND 100 AND percentage <> 'NaN'::numeric", name=op.f('ck_mh_bill_split_shares_percentage_range')),
    sa.CheckConstraint("share_amount >= 0 AND share_amount < 'Infinity'::numeric AND share_amount <> 'NaN'::numeric", name=op.f('ck_mh_bill_split_shares_nonnegative_finite_share')),
    sa.ForeignKeyConstraint(['household_id', 'member_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_bill_split_shares_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'rule_id'], ['mh_bill_split_rules.household_id', 'mh_bill_split_rules.id'], name=op.f('fk_mh_bill_split_shares_household_id_mh_bill_split_rules'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_bill_split_shares_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_bill_split_shares')),
    sa.UniqueConstraint('household_id', 'rule_id', 'member_user_id', name='uq_mh_bill_split_share_member')
    )
    op.create_index('ix_mh_bill_split_shares_member', 'mh_bill_split_shares', ['household_id', 'member_user_id'], unique=False)
    op.create_table('mh_seasonal_funds',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('contribution_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('reserve_start_date', sa.Date(), nullable=False),
    sa.Column('frequency', sa.String(length=10), server_default='monthly', nullable=False),
    sa.Column('status', sa.String(length=10), server_default='active', nullable=False),
    sa.Column('paid_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("contribution_amount > 0 AND contribution_amount < 'Infinity'::numeric AND contribution_amount <> 'NaN'::numeric", name=op.f('ck_mh_seasonal_funds_positive_finite_contribution')),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_mh_seasonal_funds_currency_code')),
    sa.CheckConstraint("frequency IN ('monthly', 'weekly')", name=op.f('ck_mh_seasonal_funds_frequency')),
    sa.CheckConstraint("paid_transaction_id IS NULL OR status IN ('paid', 'archived')", name=op.f('ck_mh_seasonal_funds_paid_reference_status')),
    sa.CheckConstraint("status IN ('active', 'paid', 'archived')", name=op.f('ck_mh_seasonal_funds_status')),
    sa.CheckConstraint("target_amount > 0 AND target_amount < 'Infinity'::numeric AND target_amount <> 'NaN'::numeric", name=op.f('ck_mh_seasonal_funds_positive_finite_target')),
    sa.CheckConstraint('length(trim(title)) > 0', name=op.f('ck_mh_seasonal_funds_title_required')),
    sa.CheckConstraint('target_date >= reserve_start_date', name=op.f('ck_mh_seasonal_funds_target_after_start')),
    sa.ForeignKeyConstraint(['household_id', 'account_id'], ['mh_financial_accounts.household_id', 'mh_financial_accounts.id'], name=op.f('fk_mh_seasonal_funds_household_id_mh_financial_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_seasonal_funds_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'paid_transaction_id'], ['mh_transactions.household_id', 'mh_transactions.id'], name=op.f('fk_mh_seasonal_funds_household_id_mh_transactions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_seasonal_funds_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_seasonal_funds')),
    sa.UniqueConstraint('household_id', 'id', name='uq_mh_seasonal_fund_tenant_id')
    )
    op.create_index('ix_mh_seasonal_funds_account', 'mh_seasonal_funds', ['household_id', 'account_id'], unique=False)
    op.create_index('ix_mh_seasonal_funds_creator', 'mh_seasonal_funds', ['household_id', 'created_by_user_id'], unique=False)
    op.create_index('ix_mh_seasonal_funds_currency_status_target', 'mh_seasonal_funds', ['household_id', 'currency', 'status', 'target_date'], unique=False)
    op.create_index('ix_mh_seasonal_funds_payment', 'mh_seasonal_funds', ['household_id', 'paid_transaction_id'], unique=False)
    op.create_table('mh_transaction_split_shares',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('member_user_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('owed_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_mh_transaction_split_shares_currency_code')),
    sa.CheckConstraint("owed_amount >= 0 AND owed_amount < 'Infinity'::numeric AND owed_amount <> 'NaN'::numeric", name=op.f('ck_mh_transaction_split_shares_nonnegative_finite_owed')),
    sa.CheckConstraint("percentage BETWEEN 0 AND 100 AND percentage <> 'NaN'::numeric", name=op.f('ck_mh_transaction_split_shares_percentage_range')),
    sa.ForeignKeyConstraint(['household_id', 'member_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_transaction_split_shares_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'transaction_id'], ['mh_transactions.household_id', 'mh_transactions.id'], name=op.f('fk_mh_transaction_split_shares_household_id_mh_transactions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_transaction_split_shares_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_transaction_split_shares')),
    sa.UniqueConstraint('household_id', 'transaction_id', 'member_user_id', name='uq_mh_transaction_split_share_member')
    )
    op.create_index('ix_mh_transaction_split_shares_member_currency', 'mh_transaction_split_shares', ['household_id', 'member_user_id', 'currency'], unique=False)
    op.add_column('mh_financial_accounts', sa.Column('scope', sa.String(length=10), nullable=True))
    op.add_column('mh_household_memberships', sa.Column('can_view_commitments', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('mh_transactions', sa.Column('scope', sa.String(length=10), nullable=True))
    op.add_column('mh_transactions', sa.Column('paid_by_user_id', sa.Uuid(), nullable=True))
    op.create_index('ix_mh_transactions_payer', 'mh_transactions', ['household_id', 'paid_by_user_id'], unique=False)
    op.create_foreign_key('fk_mh_transactions_payer_membership', 'mh_transactions', 'mh_household_memberships', ['household_id', 'paid_by_user_id'], ['household_id', 'user_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_mh_transactions_payer_membership', 'mh_transactions', type_='foreignkey')
    op.drop_index('ix_mh_transactions_payer', table_name='mh_transactions')
    op.drop_column('mh_transactions', 'paid_by_user_id')
    op.drop_column('mh_transactions', 'scope')
    op.drop_column('mh_household_memberships', 'can_view_commitments')
    op.drop_column('mh_financial_accounts', 'scope')
    op.drop_index('ix_mh_transaction_split_shares_member_currency', table_name='mh_transaction_split_shares')
    op.drop_table('mh_transaction_split_shares')
    op.drop_index('ix_mh_seasonal_funds_payment', table_name='mh_seasonal_funds')
    op.drop_index('ix_mh_seasonal_funds_currency_status_target', table_name='mh_seasonal_funds')
    op.drop_index('ix_mh_seasonal_funds_creator', table_name='mh_seasonal_funds')
    op.drop_index('ix_mh_seasonal_funds_account', table_name='mh_seasonal_funds')
    op.drop_table('mh_seasonal_funds')
    op.drop_index('ix_mh_bill_split_shares_member', table_name='mh_bill_split_shares')
    op.drop_table('mh_bill_split_shares')
    op.drop_index('ix_mh_bill_split_rules_currency', table_name='mh_bill_split_rules')
    op.drop_index('ix_mh_bill_split_rules_creator', table_name='mh_bill_split_rules')
    op.drop_table('mh_bill_split_rules')
    op.drop_index('ix_mh_tasks_tenant_status_due', table_name='mh_household_tasks')
    op.drop_index('ix_mh_tasks_tenant_creator', table_name='mh_household_tasks')
    op.drop_index('ix_mh_tasks_tenant_assignee', table_name='mh_household_tasks')
    op.drop_index('ix_mh_tasks_tenant_account', table_name='mh_household_tasks')
    op.drop_table('mh_household_tasks')
    op.drop_index('ix_mh_safe_balance_settings_user', table_name='mh_safe_balance_settings')
    op.drop_table('mh_safe_balance_settings')
    # ### end Alembic commands ###
