"""add_waitlist_leads_and_founder_reservations

Revision ID: 8398e2af0d9e
Revises: 5bbbdcd262ed
Create Date: 2026-09-30 17:55:49.185763
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8398e2af0d9e'
down_revision: Union[str, Sequence[str], None] = '5bbbdcd262ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mh_waitlist_leads',
    sa.Column('contact_kind', sa.String(length=10), nullable=False),
    sa.Column('contact_value', sa.String(length=320), nullable=False),
    sa.Column('consent_contact', sa.Boolean(), nullable=False),
    sa.Column('problem_codes', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('invite_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('referral_code', sa.String(length=32), nullable=False),
    sa.Column('referred_by_id', sa.Uuid(), nullable=True),
    sa.Column('founder_decision', sa.String(length=12), server_default='pending', nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(contact_kind = 'email' AND contact_value = lower(trim(contact_value)) AND position('@' in contact_value) > 1) OR (contact_kind = 'phone' AND contact_value ~ '^\\+[1-9][0-9]{1,14}$')", name=op.f('ck_mh_waitlist_leads_normalized_contact')),
    sa.CheckConstraint("(founder_decision = 'reserved' AND reserved_at IS NOT NULL) OR (founder_decision <> 'reserved' AND reserved_at IS NULL)", name=op.f('ck_mh_waitlist_leads_reservation_consistency')),
    sa.CheckConstraint("contact_kind IN ('email', 'phone')", name=op.f('ck_mh_waitlist_leads_contact_kind')),
    sa.CheckConstraint("founder_decision IN ('pending', 'reserved', 'free')", name=op.f('ck_mh_waitlist_leads_founder_decision')),
    sa.CheckConstraint("json_typeof(problem_codes) = 'array'", name=op.f('ck_mh_waitlist_leads_problem_codes_array')),
    sa.CheckConstraint('consent_contact = true', name=op.f('ck_mh_waitlist_leads_explicit_consent')),
    sa.CheckConstraint('length(trim(contact_value)) > 0', name=op.f('ck_mh_waitlist_leads_contact_required')),
    sa.CheckConstraint('length(trim(referral_code)) > 0', name=op.f('ck_mh_waitlist_leads_referral_code_required')),
    sa.CheckConstraint('referred_by_id IS NULL OR referred_by_id <> id', name=op.f('ck_mh_waitlist_leads_not_self_referred')),
    sa.ForeignKeyConstraint(['referred_by_id'], ['mh_waitlist_leads.id'], name=op.f('fk_mh_waitlist_leads_referred_by_id_mh_waitlist_leads'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_waitlist_leads')),
    sa.UniqueConstraint('contact_kind', 'contact_value', name='uq_mh_waitlist_lead_contact'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_index('ix_mh_waitlist_leads_decision', 'mh_waitlist_leads', ['founder_decision'], unique=False)
    op.create_index('ix_mh_waitlist_leads_referral', 'mh_waitlist_leads', ['referred_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mh_waitlist_leads_referral', table_name='mh_waitlist_leads')
    op.drop_index('ix_mh_waitlist_leads_decision', table_name='mh_waitlist_leads')
    op.drop_table('mh_waitlist_leads')
    # ### end Alembic commands ###
