"""add_transaction_audit_events

Revision ID: 90e7e5211dbb
Revises: 8398e2af0d9e
Create Date: 2026-10-01 06:41:46.682121
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '90e7e5211dbb'
down_revision: Union[str, Sequence[str], None] = '8398e2af0d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mh_transaction_audit_events',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('before_data', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('after_data', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
    sa.Column('changed_fields', sa.JSON(), server_default=sa.text("'[]'::json"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(action = 'auto_created' AND actor_user_id IS NULL) OR (action <> 'auto_created' AND actor_user_id IS NOT NULL)", name=op.f('ck_mh_transaction_audit_events_actor_for_action')),
    sa.CheckConstraint("(before_data::jsonb - ARRAY['account_id', 'category_id', 'kind', 'amount', 'transaction_date', 'description']) = '{}'::jsonb AND (after_data::jsonb - ARRAY['account_id', 'category_id', 'kind', 'amount', 'transaction_date', 'description']) = '{}'::jsonb", name=op.f('ck_mh_transaction_audit_events_snapshot_fields')),
    sa.CheckConstraint("action IN ('created', 'updated', 'deleted', 'auto_created')", name=op.f('ck_mh_transaction_audit_events_action')),
    sa.CheckConstraint("json_typeof(before_data) = 'object' AND json_typeof(after_data) = 'object'", name=op.f('ck_mh_transaction_audit_events_snapshot_objects')),
    sa.CheckConstraint('json_typeof(changed_fields) = \'array\' AND changed_fields::jsonb <@ \'["account_id", "category_id", "kind", "amount", "transaction_date", "description"]\'::jsonb', name=op.f('ck_mh_transaction_audit_events_changed_fields_allowed')),
    sa.ForeignKeyConstraint(['household_id', 'actor_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_transaction_audit_events_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'transaction_id'], ['mh_transactions.household_id', 'mh_transactions.id'], name=op.f('fk_mh_transaction_audit_events_household_id_mh_transactions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_transaction_audit_events'))
    )
    op.create_index('ix_mh_transaction_audit_events_history', 'mh_transaction_audit_events', ['household_id', 'transaction_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mh_transaction_audit_events_history', table_name='mh_transaction_audit_events')
    op.drop_table('mh_transaction_audit_events')
    # ### end Alembic commands ###
