"""household_member_permissions_and_account_restrictions

Revision ID: 9c13941e47f1
Revises: 2e30efc792c8
Create Date: 2026-10-01 12:32:09.352691
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9c13941e47f1'
down_revision: Union[str, Sequence[str], None] = '2e30efc792c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mh_household_account_restrictions',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('member_user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id', 'account_id'], ['mh_financial_accounts.household_id', 'mh_financial_accounts.id'], name=op.f('fk_mh_household_account_restrictions_household_id_mh_financial_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'member_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_household_account_restrictions_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_household_account_restrictions_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_household_account_restrictions')),
    sa.UniqueConstraint('household_id', 'member_user_id', 'account_id', name='uq_mh_account_restriction_member_account')
    )
    op.create_index('ix_mh_account_restrictions_household_account', 'mh_household_account_restrictions', ['household_id', 'account_id'], unique=False)
    op.create_index('ix_mh_account_restrictions_household_member', 'mh_household_account_restrictions', ['household_id', 'member_user_id'], unique=False)
    op.add_column('mh_household_memberships', sa.Column('can_add_transactions', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('mh_household_memberships', sa.Column('can_edit_budgets', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mh_household_memberships', 'can_edit_budgets')
    op.drop_column('mh_household_memberships', 'can_add_transactions')
    op.drop_index('ix_mh_account_restrictions_household_member', table_name='mh_household_account_restrictions')
    op.drop_index('ix_mh_account_restrictions_household_account', table_name='mh_household_account_restrictions')
    op.drop_table('mh_household_account_restrictions')
    # ### end Alembic commands ###
