"""stabilize_category_name_uniqueness

Revision ID: adb5e7aeef16
Revises: 091abbeecadc
Create Date: 2026-09-28 16:14:53.077405
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'adb5e7aeef16'
down_revision: Union[str, Sequence[str], None] = '091abbeecadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_mh_category_name'), table_name='mh_categories')
    op.create_unique_constraint('uq_mh_category_name', 'mh_categories', ['household_id', 'kind', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_mh_category_name', 'mh_categories', type_='unique')
    op.create_index(op.f('uq_mh_category_name'), 'mh_categories', ['household_id', 'kind', sa.literal_column('lower(TRIM(BOTH FROM name))')], unique=True)
    # ### end Alembic commands ###
