"""add_hashed_authentication_attempt_throttle

Revision ID: bc746110ce85
Revises: 442f008114e7
Create Date: 2026-10-02 17:14:20.307085
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bc746110ce85'
down_revision: Union[str, Sequence[str], None] = '442f008114e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mh_authentication_attempts',
    sa.Column('identifier_digest', sa.String(length=64), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("identifier_digest ~ '^[0-9a-f]{64}$'", name=op.f('ck_mh_authentication_attempts_identifier_sha256_digest')),
    sa.CheckConstraint('attempt_count BETWEEN 1 AND 100', name=op.f('ck_mh_authentication_attempts_bounded_positive_attempt_count')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_authentication_attempts')),
    sa.UniqueConstraint('identifier_digest')
    )
    op.create_index('ix_mh_authentication_attempts_locked_until', 'mh_authentication_attempts', ['locked_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mh_authentication_attempts_locked_until', table_name='mh_authentication_attempts')
    op.drop_table('mh_authentication_attempts')
    # ### end Alembic commands ###
