"""add_savings_goals_and_allocations

Revision ID: c7c95525da13
Revises: cb1638c233ef
Create Date: 2026-09-30 03:00:14.577501
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c7c95525da13'
down_revision: Union[str, Sequence[str], None] = 'cb1638c233ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mh_savings_goals',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), server_default='', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_amount > 0 AND target_amount < 'Infinity'::numeric", name=op.f('ck_mh_savings_goals_positive_finite_target')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_mh_savings_goals_name_required')),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_savings_goals_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_savings_goals_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_savings_goals')),
    sa.UniqueConstraint('household_id', 'id', name='uq_mh_savings_goal_tenant_id')
    )
    op.create_index('ix_mh_savings_goals_household_archived', 'mh_savings_goals', ['household_id', 'is_archived'], unique=False)
    op.create_table('mh_savings_goal_allocations',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('event_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("amount <> 0 AND amount > '-Infinity'::numeric AND amount < 'Infinity'::numeric", name=op.f('ck_mh_savings_goal_allocations_nonzero_finite_amount')),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_savings_goal_allocations_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'goal_id'], ['mh_savings_goals.household_id', 'mh_savings_goals.id'], name=op.f('fk_mh_savings_goal_allocations_household_id_mh_savings_goals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_savings_goal_allocations_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_savings_goal_allocations'))
    )
    op.create_index('ix_mh_savings_allocations_household_goal_date', 'mh_savings_goal_allocations', ['household_id', 'goal_id', 'event_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mh_savings_allocations_household_goal_date', table_name='mh_savings_goal_allocations')
    op.drop_table('mh_savings_goal_allocations')
    op.drop_index('ix_mh_savings_goals_household_archived', table_name='mh_savings_goals')
    op.drop_table('mh_savings_goals')
    # ### end Alembic commands ###
