"""add_recurring_transaction_rules_and_occurrence_identity

Revision ID: cb1638c233ef
Revises: adb5e7aeef16
Create Date: 2026-09-29 20:39:05.572564
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb1638c233ef'
down_revision: Union[str, Sequence[str], None] = 'adb5e7aeef16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mh_recurring_transaction_rules',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=10), server_default='expense', nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), server_default='0', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('frequency', sa.String(length=10), server_default='monthly', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('next_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("amount > 0 AND amount <> 'NaN'::numeric", name=op.f('ck_mh_recurring_transaction_rules_positive_amount')),
    sa.CheckConstraint("frequency IN ('daily', 'weekly', 'monthly')", name=op.f('ck_mh_recurring_transaction_rules_frequency')),
    sa.CheckConstraint("kind IN ('income', 'expense')", name=op.f('ck_mh_recurring_transaction_rules_kind')),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name=op.f('ck_mh_recurring_transaction_rules_end_date_after_start')),
    sa.CheckConstraint('next_date >= start_date', name=op.f('ck_mh_recurring_transaction_rules_next_date_after_start')),
    sa.ForeignKeyConstraint(['household_id', 'account_id'], ['mh_financial_accounts.household_id', 'mh_financial_accounts.id'], name=op.f('fk_mh_recurring_transaction_rules_household_id_mh_financial_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'category_id', 'kind'], ['mh_categories.household_id', 'mh_categories.id', 'mh_categories.kind'], name=op.f('fk_mh_recurring_transaction_rules_household_id_mh_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_recurring_transaction_rules_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_recurring_transaction_rules_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_recurring_transaction_rules')),
    sa.UniqueConstraint('household_id', 'id', name='uq_mh_recurring_rule_tenant_id')
    )
    op.create_index('ix_mh_recurring_rules_tenant_active_next', 'mh_recurring_transaction_rules', ['household_id', 'is_active', 'next_date'], unique=False)
    op.add_column('mh_transactions', sa.Column('recurring_rule_id', sa.Uuid(), nullable=True))
    op.add_column('mh_transactions', sa.Column('scheduled_for', sa.Date(), nullable=True))
    op.create_unique_constraint('uq_mh_transaction_recurring_occurrence', 'mh_transactions', ['household_id', 'recurring_rule_id', 'scheduled_for'])
    op.create_foreign_key(op.f('fk_mh_transactions_household_id_mh_recurring_transaction_rules'), 'mh_transactions', 'mh_recurring_transaction_rules', ['household_id', 'recurring_rule_id'], ['household_id', 'id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_mh_transactions_household_id_mh_recurring_transaction_rules'), 'mh_transactions', type_='foreignkey')
    op.drop_constraint('uq_mh_transaction_recurring_occurrence', 'mh_transactions', type_='unique')
    op.drop_column('mh_transactions', 'scheduled_for')
    op.drop_column('mh_transactions', 'recurring_rule_id')
    op.drop_index('ix_mh_recurring_rules_tenant_active_next', table_name='mh_recurring_transaction_rules')
    op.drop_table('mh_recurring_transaction_rules')
    # ### end Alembic commands ###
