"""budget_currency_schema

Revision ID: e592651049ff
Revises: 90e7e5211dbb
Create Date: 2026-10-01 12:22:28.343839
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e592651049ff'
down_revision: Union[str, Sequence[str], None] = '90e7e5211dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mh_monthly_category_budgets', sa.Column('currency', sa.String(length=3), server_default='SAR', nullable=False))
    op.drop_constraint(op.f('uq_mh_budget_category_month'), 'mh_monthly_category_budgets', type_='unique')
    op.create_unique_constraint('uq_mh_budget_category_month_currency', 'mh_monthly_category_budgets', ['household_id', 'category_id', 'year', 'month', 'currency'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_mh_budget_category_month_currency', 'mh_monthly_category_budgets', type_='unique')
    op.create_unique_constraint(op.f('uq_mh_budget_category_month'), 'mh_monthly_category_budgets', ['household_id', 'category_id', 'year', 'month'], postgresql_nulls_not_distinct=False)
    op.drop_column('mh_monthly_category_budgets', 'currency')
    # ### end Alembic commands ###
