"""add_transfers_bills_reminder_occurrences

Revision ID: fbb2c9cb70ba
Revises: 9c13941e47f1
Create Date: 2026-10-01 17:54:13.612420
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fbb2c9cb70ba'
down_revision: Union[str, Sequence[str], None] = '9c13941e47f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mh_account_transfers',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('source_account_id', sa.Uuid(), nullable=False),
    sa.Column('destination_account_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("amount > 0 AND amount < 'Infinity'::numeric AND amount <> 'NaN'::numeric", name=op.f('ck_mh_account_transfers_positive_finite_amount')),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_mh_account_transfers_currency_code')),
    sa.CheckConstraint('source_account_id <> destination_account_id', name=op.f('ck_mh_account_transfers_distinct_accounts')),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_account_transfers_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'destination_account_id'], ['mh_financial_accounts.household_id', 'mh_financial_accounts.id'], name='fk_mh_account_transfers_destination_account', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'source_account_id'], ['mh_financial_accounts.household_id', 'mh_financial_accounts.id'], name='fk_mh_account_transfers_source_account', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_account_transfers_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_account_transfers'))
    )
    op.create_index('ix_mh_account_transfers_destination_date', 'mh_account_transfers', ['household_id', 'destination_account_id', 'transfer_date'], unique=False)
    op.create_index('ix_mh_account_transfers_source_date', 'mh_account_transfers', ['household_id', 'source_account_id', 'transfer_date'], unique=False)
    op.create_table('mh_bills',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='unpaid', nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.Column('remind_days', sa.Integer(), server_default='3', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'paid' AND paid_on IS NOT NULL) OR (status = 'unpaid' AND paid_on IS NULL)", name=op.f('ck_mh_bills_paid_date_consistency')),
    sa.CheckConstraint("amount > 0 AND amount < 'Infinity'::numeric AND amount <> 'NaN'::numeric", name=op.f('ck_mh_bills_positive_finite_amount')),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_mh_bills_currency_code')),
    sa.CheckConstraint("status IN ('unpaid', 'paid')", name=op.f('ck_mh_bills_status')),
    sa.CheckConstraint('length(trim(title)) > 0', name=op.f('ck_mh_bills_title_required')),
    sa.CheckConstraint('remind_days BETWEEN 0 AND 365', name=op.f('ck_mh_bills_remind_days_range')),
    sa.ForeignKeyConstraint(['household_id', 'account_id'], ['mh_financial_accounts.household_id', 'mh_financial_accounts.id'], name=op.f('fk_mh_bills_household_id_mh_financial_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'created_by_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_bills_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_bills_household_id_mh_households'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_bills')),
    sa.UniqueConstraint('household_id', 'id', name='uq_mh_bill_tenant_id')
    )
    op.create_index('ix_mh_bills_household_account_due', 'mh_bills', ['household_id', 'account_id', 'due_date'], unique=False)
    op.create_index('ix_mh_bills_household_due', 'mh_bills', ['household_id', 'due_date'], unique=False)
    op.create_table('mh_reminder_deliveries',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=10), server_default='in_app', nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('bill_id', sa.Uuid(), nullable=True),
    sa.Column('installment_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(source_kind = 'bill' AND bill_id IS NOT NULL AND bill_id = source_id AND installment_id IS NULL) OR (source_kind = 'installment' AND installment_id IS NOT NULL AND installment_id = source_id AND bill_id IS NULL)", name=op.f('ck_mh_reminder_deliveries_source_reference')),
    sa.CheckConstraint("(status = 'sent' AND delivered_at IS NOT NULL) OR (status <> 'sent' AND delivered_at IS NULL)", name=op.f('ck_mh_reminder_deliveries_delivery_time')),
    sa.CheckConstraint("channel IN ('in_app', 'email')", name=op.f('ck_mh_reminder_deliveries_channel')),
    sa.CheckConstraint("source_kind IN ('bill', 'installment')", name=op.f('ck_mh_reminder_deliveries_source_kind')),
    sa.CheckConstraint("status IN ('pending', 'sent', 'failed', 'suppressed')", name=op.f('ck_mh_reminder_deliveries_status')),
    sa.ForeignKeyConstraint(['household_id', 'bill_id'], ['mh_bills.household_id', 'mh_bills.id'], name=op.f('fk_mh_reminder_deliveries_household_id_mh_bills'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id', 'recipient_user_id'], ['mh_household_memberships.household_id', 'mh_household_memberships.user_id'], name=op.f('fk_mh_reminder_deliveries_household_id_mh_household_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['mh_households.id'], name=op.f('fk_mh_reminder_deliveries_household_id_mh_households'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['installment_id'], ['mh_debt_installments.id'], name=op.f('fk_mh_reminder_deliveries_installment_id_mh_debt_installments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mh_reminder_deliveries')),
    sa.UniqueConstraint('household_id', 'recipient_user_id', 'channel', 'source_kind', 'source_id', 'due_date', name='uq_mh_reminder_delivery_occurrence')
    )
    op.create_index('ix_mh_reminder_deliveries_pending', 'mh_reminder_deliveries', ['household_id', 'channel', 'status', 'scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mh_reminder_deliveries_pending', table_name='mh_reminder_deliveries')
    op.drop_table('mh_reminder_deliveries')
    op.drop_index('ix_mh_bills_household_due', table_name='mh_bills')
    op.drop_index('ix_mh_bills_household_account_due', table_name='mh_bills')
    op.drop_table('mh_bills')
    op.drop_index('ix_mh_account_transfers_source_date', table_name='mh_account_transfers')
    op.drop_index('ix_mh_account_transfers_destination_date', table_name='mh_account_transfers')
    op.drop_table('mh_account_transfers')
    # ### end Alembic commands ###
